#!/bin/sh

set -e

cd $(dirname "$0")

context=${CONTEXT:-400000}
model=${MODEL:-"../../models/Qwen3-Coder-Next-Q4_K_M.gguf"}

../../llama.cpp/build/bin/llama-cli \
  -m $model \
  -ngl 999 \
  --ctx-size $context \
  -n 8192 \
  -b 2048 \
  -ub 2048 \
  --temp 0.1
