#!/bin/sh

context=${CONTEXT:-400000}
model=${MODEL:-"../../models/Qwen3-Coder-Next-Q4_0.gguf"}

../../llama.cpp/build/bin/llama-cli \
  -m $model \
  -ngl 999 \
  --ctx-size $context \
  -n 4096 \
  --no-mmap \
  --temp 0.1
