#!/bin/sh

# For multimodal, use '--mmproj' with the image model. For example:
#
#     MODEL=../../models/Qwen3-VL-30B-A3B-Instruct-Q4_0.gguf ./llama-server --mmproj ../../models/mmproj-F16.gguf

set -e

cd $(dirname "$0")

context=${CONTEXT:-120000}
model=${MODEL:-"/home/$USER/code/ai/models/Qwen3-Coder-Next-Q4_K_M.gguf"}

export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,2}

/home/$USER/code/ai/llama.cpp/build/bin/llama-server \
  -m $model \
  -c $context \
  -n 8192 \
  -b 2048 \
  -ub 2048 \
  --no-mmap \
  --temp 1.0 \
  --top-p 0.95 \
  --top-k 40 \
  --jinja \
  --host 0.0.0.0 $@
